= Spring Reactive Web Sample Project

Spring Reactive Web Sample Project based on link:https://start.spring.io/[Start Spring] (with

  - `Maven` and
  - `Spring Boot` version `2.0.0-SNAPSHOT` (`@170515`);
  - `g:de.mirb.pg.spring`;
  - `a:reactive-spring`;
  - dependencies: `Reactive Web`).

Also greatly inspired by this link:https://www.youtube.com/watch?v=zVNIZXf4BG8&t=1671s[talk from Josh Long] and according link:https://github.com/joshlong/flux-flix-service[GitHub Repo].

[ TOC ]

== Disclaimer
Current source code and version is published without license. +
If you (somebody) want to use this in his project please contact me.
Afterwards I will grant the use of this code without warranty.
When I find some time to inform myself about the different possible licenses at link:http://choosealicense.com[choosealicense.com]
I will probably change to a suitable license.

== General information
Build a sample `Spring Reactive Web App`

== Start/Run Application

To start the application via Maven (Shell) use `mvn spring-boot:run`.

== Sample requests
For sample request link:https://httpie.org/[HTTPie] is used.

  * Single event: `http localhost:8080/events/123`
  * List of events: `http localhost:8080/events amount:50`
  * Infinite stream of events: `http -S localhost:8080/events amount:50`

Or via `curl`

  * Single event: `curl http://localhost:8080/events/123 | json_pp`
  * List of events (100): `curl -H "amount:100" http://localhost:8080/events | json_pp`
  * Stream of infinite events: `curl http://localhost:8080/infinite | json_pp`

== Helpful links

  * link:https://dzone.com/articles/spring-webflux-first-steps[DZone: First steps]
  * link:https://dzone.com/articles/spring-reactive-samples[DZone: Reactive Sample]
  * link:https://spring.io/blog/2017/02/23/spring-framework-5-0-m5-update[WebClient]
