= Spring Reactive Web Sample Project

Spring Reactive Web Sample Project based on link:https://start.spring.io/[Start Spring] (with

  - `Maven` and
  - `Spring Boot` version `2.0.0-SNAPSHOT` (`@170515`);
  - `g:de.mirb.pg.spring`;
  - `a:reactive-spring`;
  - dependencies: `Reactive Web`).

Also greatly inspired by this link:https://www.youtube.com/watch?v=zVNIZXf4BG8&t=1671s[talk from Josh Long] and according link:https://github.com/joshlong/flux-flix-service[GitHub Repo].

[ TOC ]

== Disclaimer
Current source code and version is published without license. +
If you (somebody) want to use this in his project please contact me.
Afterwards I will grant the use of this code without warranty.
When I find some time to inform myself about the different possible licenses at link:http://choosealicense.com[choosealicense.com]
I will probably change to a suitable license.

== General information
Build a sample `Spring Reactive Web App`

== Current Features _(for latest stable version)_

  * Get `Event` stream finite/infinite and get a single `Event`

== New and Noteworthy

  * Version `0.2.0-SNAPSHOT`
    ** _TBD_: Refactoring in separate modules.
  * Version `0.1.0`
    ** First release which includes `Events` sample in the `event-server`



== Start/Run Application

To start the application via Maven (Shell) change into the `events-server` module and follow the instructions in the `README` file.

== Helpful links

  * link:https://dzone.com/articles/spring-webflux-first-steps[DZone: First steps]
  * link:https://dzone.com/articles/spring-reactive-samples[DZone: Reactive Sample]
  * link:https://spring.io/blog/2017/02/23/spring-framework-5-0-m5-update[WebClient]
